import { Router } from 'express';
import { pool } from '../db.js';
import { logAudit } from '../audit.js';
import { HttpError } from '../utils.js';
import { addHistory } from '../services/history.js';
import { kindLabel, teamName } from '../services/events.js';

const router = Router();

const KINDS = ['entrega', 'montagem', 'limpeza', 'retirada', 'desmontagem', 'manutencao', 'vistoria'];
const STATUSES = ['pendente', 'em_rota', 'concluido', 'nao_realizado', 'cancelado'];

function toAppt(row){
  return {
    id: row.id,
    date: row.date,
    clientId: row.client_id,
    teamId: row.team_id,
    taskIds: row.task_ids || [],
    notes: row.notes,
    status: row.status || 'pendente',
    rentalId: row.rental_id,
    siteId: row.site_id,
    kind: row.kind || 'entrega',
    timeWindow: row.time_window,
    routeOrder: row.route_order,
    items: row.items || [],
    autoGenerated: !!row.auto_generated,
  };
}

function checkEnums(body){
  if(body.kind && !KINDS.includes(body.kind)) throw new HttpError(400, 'Tipo de visita inválido.');
  if(body.status && !STATUSES.includes(body.status)) throw new HttpError(400, 'Status inválido.');
}

// Filtros opcionais: ?from=&to=&teamId=&rentalId=  (sem filtros = tudo, como antes)
router.get('/', async (req, res) => {
  const conds = [], params = [];
  if(req.query.from){ params.push(req.query.from); conds.push(`date >= $${params.length}`); }
  if(req.query.to){ params.push(req.query.to); conds.push(`date <= $${params.length}`); }
  if(req.query.teamId){ params.push(req.query.teamId); conds.push(`team_id = $${params.length}`); }
  if(req.query.rentalId){ params.push(req.query.rentalId); conds.push(`rental_id = $${params.length}`); }
  const { rows } = await pool.query(
    `SELECT * FROM appointments ${conds.length ? 'WHERE ' + conds.join(' AND ') : ''}
      ORDER BY date ASC, route_order ASC NULLS LAST, created_at ASC`,
    params
  );
  res.json(rows.map(toAppt));
});

router.post('/', async (req, res) => {
  checkEnums(req.body);
  const { id, date, clientId, teamId, taskIds, notes, rentalId, siteId, kind, timeWindow, routeOrder, items } = req.body;
  await pool.query(
    `INSERT INTO appointments (id, date, client_id, team_id, task_ids, notes, rental_id, site_id, kind, time_window, route_order, items)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,
    [id, date, clientId, teamId, JSON.stringify(taskIds || []), notes || null,
     rentalId || null, siteId || null, kind || 'entrega', timeWindow || null, routeOrder ?? null, JSON.stringify(items || [])]
  );
  const { rows } = await pool.query('SELECT name FROM clients WHERE id=$1', [clientId]);
  await logAudit(req.user, 'create', 'appointment', `${date} — ${rows[0]?.name || clientId}`, { teamId, kind });
  res.status(201).json(req.body);
});

router.put('/:id', async (req, res) => {
  checkEnums(req.body);
  const { rows: [before] } = await pool.query('SELECT * FROM appointments WHERE id=$1', [req.params.id]);
  const { date, clientId, teamId, taskIds, notes, siteId, kind, timeWindow, routeOrder, items, status } = req.body;
  await pool.query(
    `UPDATE appointments SET date=$1, client_id=$2, team_id=$3, task_ids=$4, notes=$5,
       site_id=COALESCE($6, site_id), kind=COALESCE($7, kind), time_window=$8, route_order=$9,
       items=COALESCE($10, items), status=COALESCE($11, status)
     WHERE id=$12`,
    [date, clientId, teamId, JSON.stringify(taskIds || []), notes || null,
     siteId || null, kind || null, timeWindow || null, routeOrder ?? null,
     items ? JSON.stringify(items) : null, status || null, req.params.id]
  );
  const { rows } = await pool.query('SELECT name FROM clients WHERE id=$1', [clientId]);
  await logAudit(req.user, 'update', 'appointment', `${date} — ${rows[0]?.name || clientId}`, { teamId });

  // Na O.S.: quem distribuiu para qual equipe, e remarcações de dia ou horário
  if(before?.rental_id){
    const what = `${kindLabel(before.kind)} de ${String(before.date).slice(8, 10)}/${String(before.date).slice(5, 7)}`;
    const newTeam = teamId || null;
    if((before.team_id || null) !== newTeam){
      await addHistory(null, { rentalId: before.rental_id, appointmentId: before.id, type: 'distribuida', user: req.user,
        message: newTeam
          ? (before.team_id ? `${what}: equipe trocada de ${teamName(before.team_id)} para ${teamName(newTeam)}.` : `${what} distribuída para a ${teamName(newTeam)}.`)
          : `${what}: retirada da ${teamName(before.team_id)}, aguardando equipe.` });
    }
    const changes = [];
    if(String(before.date) !== String(date)) changes.push(`dia ${String(before.date).slice(8, 10)}/${String(before.date).slice(5, 7)} → ${String(date).slice(8, 10)}/${String(date).slice(5, 7)}`);
    if((before.time_window || '') !== (req.body.timeWindow || '')) changes.push(`hora marcada ${before.time_window || 'sem horário'} → ${req.body.timeWindow || 'sem horário'}`);
    if(changes.length){
      await addHistory(null, { rentalId: before.rental_id, appointmentId: before.id, type: 'remarcada', user: req.user,
        message: `${what} remarcada: ${changes.join('; ')}.` });
    }
  }
  res.json(req.body);
});

// Reordenar a rota do dia: { order: ["idA", "idB", "idC"] }
router.put('/route/order', async (req, res) => {
  const { order } = req.body;
  if(!Array.isArray(order)) throw new HttpError(400, 'Envie a lista "order" com os IDs na sequência.');
  for(let i = 0; i < order.length; i++){
    await pool.query('UPDATE appointments SET route_order=$1 WHERE id=$2', [i + 1, order[i]]);
  }
  res.json({ ok: true });
});

router.delete('/:id', async (req, res) => {
  const { rows } = await pool.query(
    `SELECT a.date, c.name FROM appointments a LEFT JOIN clients c ON c.id = a.client_id WHERE a.id=$1`,
    [req.params.id]
  );
  await pool.query('DELETE FROM appointments WHERE id=$1', [req.params.id]);
  await logAudit(req.user, 'delete', 'appointment', rows[0] ? `${rows[0].date} — ${rows[0].name}` : null);
  res.status(204).end();
});

router.get('/:id/execution', async (req, res) => {
  const { rows } = await pool.query(
    `SELECT id, team_id, executed_tasks, notes, photos, signature, signed_by, checkin_lat, checkin_lon, created_at
       FROM execution_records WHERE appointment_id=$1 ORDER BY created_at DESC`,
    [req.params.id]
  );
  const movements = await pool.query(
    `SELECT m.movement, m.condition, m.notes, a.code FROM asset_movements m
       JOIN assets a ON a.id = m.asset_id WHERE m.appointment_id=$1 ORDER BY a.code`,
    [req.params.id]
  );
  res.json(rows.map(r => ({
    id: r.id,
    teamId: r.team_id,
    executedTasks: r.executed_tasks || [],
    notes: r.notes,
    photos: r.photos || [],
    signature: r.signature,
    signedBy: r.signed_by,
    checkin: r.checkin_lat != null ? { lat: r.checkin_lat, lon: r.checkin_lon } : null,
    assets: movements.rows,
    createdAt: r.created_at,
  })));
});

export default router;
